# Generated by Django 5.0.7 on 2024-08-01 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_log',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('member_login', models.IntegerField(unique=True)),
                ('provider', models.CharField(max_length=50)),
                ('provider_id_google', models.CharField(max_length=50)),
                ('provider_id_line', models.CharField(max_length=50)),
                ('provider_id_fb', models.CharField(max_length=50)),
                ('access_token', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 1, 20, 52, 33, 353775)),
        ),
    ]
